# Netlify build configuration for a Vite React SPA

[build]
  # Command to build the site
  command = "yarn build"
  
  # Directory to publish (Vite's default output)
  publish = "dist"

# Redirect rule for Single-Page Applications
# This ensures that all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
